# TODO Fix PHPUnit testing of only custom themes/modules
# TODO Mailhog setup
# TODO Look into Portainer
# TODO Look into traefik

name: cf
recipe: drupal8

config:
  php: 7.2
  via: apache
  webroot: web
  xdebug: false
  conf:
    php: lando/config/php.ini
    mysql: lando/config/my.cnf

services:
  database:
    type: mysql:5.7
  pma:
    type: phpmyadmin
    hosts:
      - database
  appserver:
    composer:
      phpunit/phpunit: '*'
      behat/behat: 3.3.1
    run:
      - "ln -s /usr/local/bin/composer /usr/local/bin/composer.phar"
    run_as_root:
      - "bash /app/lando/scripts/build.sh"
  node:
    type: node:6.10
    globals:
      gulp-cli: latest
    build:
      - "cd $LANDO_MOUNT && npm install"
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: 1026
  portainer:
    type: compose
    services:
      image: portainer/portainer
      ports:
        - "9001:9000"   # PHPStorm takes port 9000...
      command: -H unix:///var/run/docker.sock
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

#  Leaving this here for now, as an example of how to use other docker images
#  compass:
#    type: compose
#    services:
#      image: antonienko/compass-watch
#      command: watch --poll /src/compass
#    description: run compass- use lando compass



tooling:
  phpunit:
    service: appserver
    description: run PHPUnit- use lando phpunit
  behat:
    service: appserver
    description: run behat- use lando behat
    cmd: cd /app ; behat  # Run behat from the /app  directory
  mailhog:
    service: mailhog
  node:
    service: node
  npm:
    service: node
  gulp:
    service: node
  sendmail:
    service: appserver
    cmd: /usr/local/bin/mhsendmail
  alert:
    service: appserver
    cmd: php /app/mail.php